server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: car-inventory-service
          uri: lb://car-inventory-service
          predicates:
            - Path=/api/v1/car/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/booking/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payment/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customer/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

okta:
  oauth2:
    client-id: 5tppUjYQumrjnkE1EJyB6RVtyue3huap
    client-secret: A_37IkzKjWn39H6YwaRjejddj4HAOo1-uDviOl3N-RuGWaGdZugh7PFayp8Hjm3t
    issuer: https://dev-4ovrmt0auyizzkjn.us.auth0.com/