spring:
    application:
        name: carinventory-service
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: jdbc:postgresql://localhost:5432/ms_carinventory
        username: admin
        password: 1234

server:
    port: 8082

eureka:
    client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true